default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dataverse-360
      dataset: transaction_analytics
      threads: 1
      keyfile: 'C:\Users\RSK_T14s\Documents\Full Stack Data Project\Dataverse-360\airflow\gcp\dataverse-360-4ac58a9dbd94.json'